import "react-calendar-heatmap/dist/styles.css";
import { RiRobot3Fill } from "react-icons/ri";

export const AISummary: React.FC<{ summary: string }> = ({ summary }) => {
  return (
    <div className="bg-card p-6 rounded-2xl mt-6 drop-shadow-lg">
      <div className="flex-1 flex gap-3">
        <h4 className="text-paragraph text-sm mb-1">
          Generated by AI assistant
        </h4>
      </div>
      <div className="flex flex-col gap-3">
        <div className="flex flex-1 gap-3 items-center">
          <RiRobot3Fill />
          <h2 className="text-2xl font-bold text-heading">Summary</h2>
        </div>
        <p className="text-paragraph">{summary}</p>
      </div>
    </div>
  );
};
